// Copyright 2026 Splitfire AB (Onde Inference). All rights reserved.
// SPDX-License-Identifier: MIT OR Apache-2.0

/// Generated and convenience types for the Onde Inference SDK.
///
/// All core data types ([ChatRole], [ChatMessage], [SamplingConfig],
/// [GgufModelConfig], [InferenceResult], [StreamChunk], [EngineStatus],
/// [EngineInfo], [OndeError]) are generated by `flutter_rust_bridge_codegen`
/// and live in `frb_generated.dart/api.dart`. This file re-exports them
/// and adds a few Dart-idiomatic convenience extensions.
library;

// Re-export every public type from the FRB-generated API layer.
// After `flutter_rust_bridge_codegen generate`, consumers only need this
// import. They never have to reference the generated directory directly.
export 'frb_generated.dart/api.dart'
    show
        ChatRole,
        ChatMessage,
        SamplingConfig,
        GgufModelConfig,
        InferenceResult,
        StreamChunk,
        ToolCallInfo,
        EngineStatus,
        EngineInfo,
        OndeError,
        OndeError_NoModelLoaded,
        OndeError_AlreadyLoaded,
        OndeError_ModelBuild,
        OndeError_Inference,
        OndeError_Cancelled,
        OndeError_Other;

import 'frb_generated.dart/api.dart';

// ---------------------------------------------------------------------------
// OndeException
// ---------------------------------------------------------------------------

/// Optional Dart [Exception] wrapper around an [OndeError].
///
/// The generated bridge throws [OndeError] values directly. If your app prefers
/// working with `Exception`, you can wrap a caught [OndeError] in
/// [OndeException].
///
/// ```dart
/// try {
///   await engine.sendMessage(message: 'Hello!');
/// } on OndeError catch (e) {
///   throw OndeException(e);
/// }
/// ```
class OndeException implements Exception {
  /// The underlying structured error from the Rust engine.
  final OndeError error;

  const OndeException(this.error);

  /// Human-readable description of the error, forwarded from Rust.
  String get message => error.toString();

  @override
  String toString() => 'OndeException: $message';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OndeException &&
          runtimeType == other.runtimeType &&
          error == other.error;

  @override
  int get hashCode => error.hashCode;
}

// ---------------------------------------------------------------------------
// ChatMessage convenience factory extension
// ---------------------------------------------------------------------------

/// Convenience factory constructors for [ChatMessage].
///
/// ```dart
/// final msg = ChatMessageX.user('Hello!');
/// final sys = ChatMessageX.system('You are a helpful assistant.');
/// ```
extension ChatMessageX on ChatMessage {
  /// Creates a [ChatRole.system] message.
  static ChatMessage system(String content) =>
      ChatMessage(role: ChatRole.system, content: content);

  /// Creates a [ChatRole.user] message.
  static ChatMessage user(String content) =>
      ChatMessage(role: ChatRole.user, content: content);

  /// Creates a [ChatRole.assistant] message.
  static ChatMessage assistant(String content) =>
      ChatMessage(role: ChatRole.assistant, content: content);

  /// Returns an excerpt of [content] for display in logs or debug output.
  String get excerpt {
    const max = 60;
    return content.length > max ? '${content.substring(0, max)}…' : content;
  }
}

// ---------------------------------------------------------------------------
// SamplingConfig preset factory extension
// ---------------------------------------------------------------------------

/// Sampling configuration presets for common use-cases.
///
/// ```dart
/// final s = SamplingConfigX.deterministic();
/// await engine.setSampling(s);
/// ```
extension SamplingConfigX on SamplingConfig {
  /// Balanced creative-chat defaults:
  /// `temperature=0.7`, `topP=0.95`, `maxTokens=512`.
  static SamplingConfig defaultConfig() => SamplingConfig(
    temperature: 0.7,
    topP: 0.95,
    topK: null,
    minP: null,
    maxTokens: BigInt.from(512),
    frequencyPenalty: null,
    presencePenalty: null,
  );

  /// Greedy / fully deterministic decoding:
  /// `temperature=0.0`, `maxTokens=512`.
  ///
  /// Use for coding, fact-retrieval, or any task where reproducibility
  /// matters.
  static SamplingConfig deterministic() => SamplingConfig(
    temperature: 0.0,
    topP: null,
    topK: null,
    minP: null,
    maxTokens: BigInt.from(512),
    frequencyPenalty: null,
    presencePenalty: null,
  );

  /// Low-latency preset for memory-constrained mobile devices:
  /// `temperature=0.7`, `topP=0.95`, `maxTokens=128`.
  static SamplingConfig mobile() => SamplingConfig(
    temperature: 0.7,
    topP: 0.95,
    topK: null,
    minP: null,
    maxTokens: BigInt.from(128),
    frequencyPenalty: null,
    presencePenalty: null,
  );

  /// Returns a copy of this config with the given fields replaced.
  SamplingConfig copyWith({
    double? temperature,
    double? topP,
    BigInt? topK,
    double? minP,
    BigInt? maxTokens,
    double? frequencyPenalty,
    double? presencePenalty,
  }) => SamplingConfig(
    temperature: temperature ?? this.temperature,
    topP: topP ?? this.topP,
    topK: topK ?? this.topK,
    minP: minP ?? this.minP,
    maxTokens: maxTokens ?? this.maxTokens,
    frequencyPenalty: frequencyPenalty ?? this.frequencyPenalty,
    presencePenalty: presencePenalty ?? this.presencePenalty,
  );
}

// ---------------------------------------------------------------------------
// EngineStatus — convenience extension
// ---------------------------------------------------------------------------

/// Convenience helpers on [EngineStatus].
extension EngineStatusX on EngineStatus {
  /// Returns `true` when the engine is idle and ready to accept requests.
  bool get isReady => this == EngineStatus.ready;

  /// Returns `true` when the engine is either loading or generating.
  bool get isBusy =>
      this == EngineStatus.loading || this == EngineStatus.generating;

  /// Returns `true` when no model is loaded.
  bool get isUnloaded => this == EngineStatus.unloaded;

  /// Returns `true` when the engine is in an unrecoverable error state.
  bool get isError => this == EngineStatus.error;

  /// A short human-readable label for display in UIs.
  String get label => switch (this) {
    EngineStatus.unloaded => 'Unloaded',
    EngineStatus.loading => 'Loading…',
    EngineStatus.ready => 'Ready',
    EngineStatus.generating => 'Generating…',
    EngineStatus.error => 'Error',
  };
}

// ---------------------------------------------------------------------------
// EngineInfo — convenience extension
// ---------------------------------------------------------------------------

/// Convenience helpers on [EngineInfo].
extension EngineInfoX on EngineInfo {
  /// Conversation turn count as a plain [int] (downcast from [BigInt]).
  ///
  /// Safe because history length never exceeds [int] bounds in practice.
  int get historyLengthInt => historyLength.toInt();

  /// Returns `true` when the engine holds at least one conversation turn.
  bool get hasHistory => historyLength > BigInt.zero;
}

// ---------------------------------------------------------------------------
// InferenceResult — convenience extension
// ---------------------------------------------------------------------------

/// Convenience helpers on [InferenceResult].
extension InferenceResultX on InferenceResult {
  /// Returns `true` if generation stopped naturally (finish reason is "stop").
  bool get stoppedNaturally => finishReason == 'stop';

  /// Returns `true` if generation was truncated by the `maxTokens` limit.
  bool get truncated => finishReason == 'length';
}

// ---------------------------------------------------------------------------
// InferenceResult — tool calling extension
// ---------------------------------------------------------------------------

/// Convenience helpers on [InferenceResult] for tool calling.
extension InferenceResultToolsX on InferenceResult {
  /// Returns `true` if the model requested one or more tool calls.
  bool get hasToolCalls => toolCalls.isNotEmpty;
}
