// Copyright 2025 Onde Inference (Splitfire AB). All rights reserved.
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// OndeInference.kt
//
// Android-idiomatic wrapper around the UniFFI-generated OndeChatEngine.
//
// This file is the primary public API surface for the Onde Inference Android
// SDK. It wraps the low-level UniFFI bindings (generated by
// scripts/generate-bindings.sh into src/generated/kotlin/onde.kt) with:
//
//   1. Android-specific filesystem initialisation (HF_HOME, TMPDIR, etc.)
//   2. suspend functions backed by Dispatchers.IO
//   3. Flow<StreamChunk> for token streaming
//   4. Sensible Kotlin defaults so callers need minimal boilerplate
//
// Usage
// -----
// val onde = OndeInference(context)
//
// // Load the platform default model (Qwen 2.5 1.5B on Android)
// val elapsed = onde.loadDefaultModel(systemPrompt = "You are helpful.")
// println("Loaded in ${elapsed}s")
//
// // Multi-turn chat
// val result = onde.chat("Hello!")
// println(result.text)
//
// // Streaming
// onde.stream("Tell me a story.").collect { chunk ->
//     print(chunk.delta)
// }
//
// // Cleanup
// onde.unload()

package com.ondeinference.onde

import android.content.Context
import android.system.Os
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.withContext
import java.io.File

// ── Public re-exports ─────────────────────────────────────────────────────────
//
// Re-export UniFFI-generated types so callers only need to import from
// com.ondeinference.onde.* — no direct dependency on onde.kt generated types.

// These are generated by UniFFI from the Rust crate and land in
// src/generated/kotlin/onde.kt. They are re-exported here as typealiases
// so the public API namespace stays clean.
typealias ChatMessage     = uniffi.onde.ChatMessage
typealias ChatRole        = uniffi.onde.ChatRole
typealias SamplingConfig  = uniffi.onde.SamplingConfig
typealias GgufModelConfig = uniffi.onde.GgufModelConfig
typealias InferenceResult = uniffi.onde.InferenceResult
typealias StreamChunk     = uniffi.onde.StreamChunk
typealias EngineInfo      = uniffi.onde.EngineInfo
typealias EngineStatus    = uniffi.onde.EngineStatus
typealias InferenceError  = uniffi.onde.InferenceException

// ── OndeInference ─────────────────────────────────────────────────────────────

/**
 * On-device LLM inference engine for Android.
 *
 * Wraps the Rust/UniFFI [uniffi.onde.OndeChatEngine] with Android-specific
 * filesystem initialisation and idiomatic Kotlin coroutine APIs.
 *
 * The engine is thread-safe. All suspending functions dispatch to
 * [Dispatchers.IO] internally — call them from any coroutine scope.
 *
 * @param context Android application or activity context used to resolve
 *   the app's internal storage directory for the HuggingFace model cache.
 *   Pass `applicationContext` to avoid leaking activity references.
 *
 * @param dataDir Optional override for the root cache directory. Defaults to
 *   `context.filesDir`. Useful in tests or when the app wants to use a
 *   different storage location (e.g. external storage on devices with limited
 *   internal space).
 */
class OndeInference(
    private val context: Context,
    private val dataDir: File = context.filesDir,
) : AutoCloseable {

    // The underlying UniFFI engine — thread-safe Arc<OndeChatEngine> under the hood.
    private val engine = uniffi.onde.OndeChatEngine()

    // Tracks whether the Android filesystem environment has been seeded.
    @Volatile private var configured = false

    // ── Filesystem setup ──────────────────────────────────────────────────────

    /**
     * Seed the HuggingFace cache and temp directory environment variables.
     *
     * Must be called before any model load. [loadDefaultModel] and [loadModel]
     * call this automatically, so explicit calls are only needed if you want
     * to control timing (e.g. at app startup).
     *
     * Sets:
     * - `HF_HOME`              → `<dataDir>/models`
     * - `HF_HUB_CACHE`         → `<dataDir>/models/hub`
     * - `HUGGINGFACE_HUB_CACHE`→ `<dataDir>/models/hub`
     * - `TMPDIR`               → `<dataDir>/tmp`
     *
     * This is idempotent — safe to call multiple times.
     */
    fun setup() {
        if (configured) return

        val hfHome     = File(dataDir, "models").also { it.mkdirs() }
        val hfHubCache = File(hfHome,  "hub").also   { it.mkdirs() }
        val tmpDir     = File(dataDir, "tmp").also   { it.mkdirs() }

        Os.setenv("HF_HOME",               hfHome.absolutePath,     true)
        Os.setenv("HF_HUB_CACHE",          hfHubCache.absolutePath, true)
        Os.setenv("HUGGINGFACE_HUB_CACHE", hfHubCache.absolutePath, true)
        Os.setenv("TMPDIR",                tmpDir.absolutePath,      true)

        configured = true
    }

    /**
     * Resolve the directory where HuggingFace model files are stored.
     *
     * Returns the path even if setup has not been called yet.
     */
    val modelCacheDir: File
        get() = File(File(dataDir, "models"), "hub")

    // ── Model lifecycle ───────────────────────────────────────────────────────

    /**
     * Load the platform-appropriate default model.
     *
     * On Android this is **Qwen 2.5 1.5B (GGUF Q4_K_M, ~941 MB)**,
     * running on CPU via the Candle backend.
     *
     * If the model is not already cached locally it will be downloaded from
     * HuggingFace Hub on first call — ensure the app has INTERNET permission
     * and sufficient storage space (~1 GB free).
     *
     * @param systemPrompt Optional system prompt injected before the first turn.
     * @param sampling Optional sampling configuration. Defaults to
     *   [SamplingConfig.defaultSamplingConfig] when null.
     * @return Wall-clock model loading time in seconds.
     * @throws InferenceError.ModelBuild if the model cannot be loaded.
     */
    suspend fun loadDefaultModel(
        systemPrompt: String?    = null,
        sampling: SamplingConfig? = null,
    ): Double = withContext(Dispatchers.IO) {
        ensureConfigured()
        engine.loadDefaultModel(
            systemPrompt = systemPrompt,
            sampling     = sampling,
        )
    }

    /**
     * Load a specific GGUF model.
     *
     * @param config Model repository and filename configuration.
     * @param systemPrompt Optional system prompt.
     * @param sampling Optional sampling configuration.
     * @return Wall-clock model loading time in seconds.
     * @throws InferenceError.ModelBuild if the model cannot be loaded.
     * @throws InferenceError.AlreadyLoaded if a model is already loaded —
     *   call [unload] first.
     */
    suspend fun loadModel(
        config: GgufModelConfig,
        systemPrompt: String?    = null,
        sampling: SamplingConfig? = null,
    ): Double = withContext(Dispatchers.IO) {
        ensureConfigured()
        engine.loadGgufModel(
            config       = config,
            systemPrompt = systemPrompt,
            sampling     = sampling,
        )
    }

    /**
     * Unload the current model and free all associated memory.
     *
     * @return The display name of the model that was unloaded, or null if no
     *   model was loaded.
     */
    suspend fun unload(): String? = withContext(Dispatchers.IO) {
        engine.unloadModel()
    }

    /**
     * Check whether a model is currently loaded and ready.
     */
    suspend fun isLoaded(): Boolean = withContext(Dispatchers.IO) {
        engine.isLoaded()
    }

    // ── Inference ─────────────────────────────────────────────────────────────

    /**
     * Send a user message and receive a complete assistant reply.
     *
     * The user turn and assistant reply are automatically appended to the
     * engine's conversation history.
     *
     * @param message The user's message text.
     * @return The completed inference result including generated text and timing.
     * @throws InferenceError.NoModelLoaded if no model has been loaded.
     * @throws InferenceError.Inference if inference fails at runtime.
     */
    suspend fun chat(message: String): InferenceResult =
        withContext(Dispatchers.IO) { engine.sendMessage(message) }

    /**
     * Stream a user message, emitting each token delta as it is generated.
     *
     * The user turn and assembled assistant reply are automatically appended
     * to the conversation history when streaming completes.
     *
     * Collect the returned [Flow] from a coroutine scope tied to a UI
     * lifecycle to ensure automatic cancellation:
     *
     * ```kotlin
     * lifecycleScope.launch {
     *     onde.stream("Tell me a joke.").collect { chunk ->
     *         textView.append(chunk.delta)
     *     }
     * }
     * ```
     *
     * @param message The user's message text.
     * @return A cold [Flow] that emits [StreamChunk] values including a final
     *   chunk with [StreamChunk.done] set to true.
     */
    fun stream(message: String): Flow<StreamChunk> = callbackFlow {
        val listener = object : uniffi.onde.StreamChunkListener {
            override fun onChunk(chunk: StreamChunk): Boolean {
                val result = trySend(chunk)
                // Stop if the downstream collector has cancelled.
                return result.isSuccess && !chunk.done
            }
        }
        withContext(Dispatchers.IO) {
            uniffi.onde.streamChatMessage(
                engine   = engine,
                message  = message,
                listener = listener,
            )
        }
        awaitClose()
    }

    /**
     * Run a one-shot inference on an explicit message list WITHOUT modifying
     * the engine's conversation history.
     *
     * Useful for parallel prompt enhancement, summarisation, or any task where
     * you want to keep the main chat history clean.
     *
     * @param messages Explicit list of messages to run inference on.
     * @param sampling Optional sampling configuration override.
     */
    suspend fun generate(
        messages: List<ChatMessage>,
        sampling: SamplingConfig? = null,
    ): InferenceResult = withContext(Dispatchers.IO) {
        engine.generate(messages = messages, sampling = sampling)
    }

    // ── Engine state ──────────────────────────────────────────────────────────

    /**
     * Get a snapshot of the engine's current state.
     *
     * @return [EngineInfo] describing load status, model name, approximate
     *   memory, and conversation history length.
     */
    suspend fun info(): EngineInfo = withContext(Dispatchers.IO) { engine.info() }

    // ── System prompt ─────────────────────────────────────────────────────────

    /**
     * Set or replace the system prompt without reloading the model.
     *
     * Takes effect on the next inference call.
     */
    suspend fun setSystemPrompt(prompt: String) = withContext(Dispatchers.IO) {
        engine.setSystemPrompt(prompt)
    }

    /**
     * Clear the system prompt.
     */
    suspend fun clearSystemPrompt() = withContext(Dispatchers.IO) {
        engine.clearSystemPrompt()
    }

    // ── Sampling ──────────────────────────────────────────────────────────────

    /**
     * Replace the sampling configuration without reloading the model.
     *
     * Takes effect on the next inference call.
     */
    suspend fun setSampling(sampling: SamplingConfig) = withContext(Dispatchers.IO) {
        engine.setSampling(sampling)
    }

    // ── Conversation history ──────────────────────────────────────────────────

    /**
     * Get a copy of the full conversation history.
     */
    suspend fun history(): List<ChatMessage> = withContext(Dispatchers.IO) {
        engine.history()
    }

    /**
     * Clear the conversation history while keeping the model loaded.
     *
     * @return The number of turns that were removed.
     */
    suspend fun clearHistory(): ULong = withContext(Dispatchers.IO) {
        engine.clearHistory()
    }

    /**
     * Append a message to the conversation history without running inference.
     *
     * Useful for injecting context or restoring a previous session.
     */
    suspend fun pushHistory(message: ChatMessage) = withContext(Dispatchers.IO) {
        engine.pushHistory(message)
    }

    // ── AutoCloseable ─────────────────────────────────────────────────────────

    /**
     * Release all native resources held by this engine.
     *
     * The underlying Rust engine is reference-counted via [Arc] — this call
     * decrements the count and frees memory when the count reaches zero.
     * Safe to call multiple times.
     */
    override fun close() {
        engine.destroy()
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    private fun ensureConfigured() {
        if (!configured) setup()
    }
}

// ── Convenience constructors ──────────────────────────────────────────────────

/**
 * Construct preconfigured [SamplingConfig] instances without importing the
 * generated uniffi package directly.
 */
object OndeSampling {
    /** Creative chat defaults — temperature 0.7, top_p 0.95, max 512 tokens. */
    fun default(): SamplingConfig     = uniffi.onde.defaultSamplingConfig()
    /** Greedy/deterministic — temperature 0.0, max 512 tokens. */
    fun deterministic(): SamplingConfig = uniffi.onde.deterministicSamplingConfig()
    /** Conservative mobile — temperature 0.7, max 128 tokens. */
    fun mobile(): SamplingConfig      = uniffi.onde.mobileSamplingConfig()
}

/**
 * Construct [GgufModelConfig] instances for supported Onde models.
 */
object OndeModels {
    /** Platform-appropriate default — Qwen 2.5 1.5B on Android (~941 MB). */
    fun default(): GgufModelConfig  = uniffi.onde.defaultModelConfig()
    /** Qwen 2.5 1.5B Instruct GGUF Q4_K_M (~941 MB). */
    fun qwen25_1_5b(): GgufModelConfig = uniffi.onde.qwen2515bConfig()
    /** Qwen 2.5 3B Instruct GGUF Q4_K_M (~1.93 GB). */
    fun qwen25_3b(): GgufModelConfig   = uniffi.onde.qwen253bConfig()
}

/**
 * Construct [ChatMessage] values without importing the generated package.
 */
object OndeMessage {
    fun system(content: String): ChatMessage    = uniffi.onde.systemMessage(content)
    fun user(content: String): ChatMessage      = uniffi.onde.userMessage(content)
    fun assistant(content: String): ChatMessage = uniffi.onde.assistantMessage(content)
}
