// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: type=lint, unused_import, unnecessary_import

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Return the platform-appropriate default `GgufModelConfig`.
///
/// Selects the 1.5B model on iOS / tvOS / Android and the 3B model on
/// macOS / Windows / Linux.
GgufModelConfig defaultModelConfig() =>
    RustLib.instance.api.crateApiDefaultModelConfig();

/// `GgufModelConfig` for Qwen 2.5 1.5B Instruct Q4_K_M (~941 MB).
GgufModelConfig qwen2515BConfig() =>
    RustLib.instance.api.crateApiQwen2515BConfig();

/// `GgufModelConfig` for Qwen 2.5 3B Instruct Q4_K_M (~1.93 GB).
GgufModelConfig qwen253BConfig() =>
    RustLib.instance.api.crateApiQwen253BConfig();

/// `GgufModelConfig` for Qwen 2.5 Coder 1.5B Instruct Q4_K_M (~941 MB).
GgufModelConfig qwen25Coder15BConfig() =>
    RustLib.instance.api.crateApiQwen25Coder15BConfig();

/// `GgufModelConfig` for Qwen 2.5 Coder 3B Instruct Q4_K_M (~1.93 GB).
GgufModelConfig qwen25Coder3BConfig() =>
    RustLib.instance.api.crateApiQwen25Coder3BConfig();

/// Default sampling config: `temperature=0.7`, `top_p=0.95`, `max_tokens=512`.
SamplingConfig defaultSamplingConfig() =>
    RustLib.instance.api.crateApiDefaultSamplingConfig();

/// Deterministic sampling config: `temperature=0.0`, greedy, `max_tokens=512`.
SamplingConfig deterministicSamplingConfig() =>
    RustLib.instance.api.crateApiDeterministicSamplingConfig();

/// Mobile sampling config: `temperature=0.7`, `top_p=0.95`, `max_tokens=128`.
SamplingConfig mobileSamplingConfig() =>
    RustLib.instance.api.crateApiMobileSamplingConfig();

/// Seed the HuggingFace cache environment for sandboxed platforms.
///
/// On iOS (and Android), the default `~/.cache/huggingface/hub` path is outside
/// the app sandbox and writes fail with `Operation not permitted (os error 1)`.
///
/// Call this **once** at startup — before any `load_gguf_model` or
/// `download_model` — with the app's writable data directory.
///
/// # Dart usage
///
/// ```dart
/// import 'package:path_provider/path_provider.dart';
///
/// final dir = await getApplicationSupportDirectory();
/// configureCacheDir(appDataDir: dir.path);
/// ```
///
/// Internally this:
/// 1. Creates `<app_data_dir>/huggingface/hub/` if it doesn't exist.
/// 2. Sets the `HF_HOME` and `HF_HUB_CACHE` environment variables.
/// 3. Seeds `mistralrs_core::GLOBAL_HF_CACHE` so the model loader never
///    falls back to `Cache::default()`.
void configureCacheDir({required String appDataDir}) =>
    RustLib.instance.api.crateApiConfigureCacheDir(appDataDir: appDataDir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OndeChatEngine>>
abstract class OndeChatEngine implements RustOpaqueInterface {
  /// Clear the conversation history while keeping the model loaded.
  ///
  /// Returns the number of turns that were removed.
  Future<BigInt> clearHistory();

  /// Clear the current system prompt.
  Future<void> clearSystemPrompt();

  /// One-shot generation from an explicit message list.
  ///
  /// Does **not** modify the conversation history.
  Future<InferenceResult> generate(
      {required List<ChatMessage> messages, SamplingConfig? sampling});

  /// Returns a clone of the full conversation history.
  Future<List<ChatMessage>> history();

  /// Returns a point-in-time snapshot of the engine's state.
  Future<EngineInfo> info();

  /// Returns `true` if a model is currently loaded and ready.
  Future<bool> isLoaded();

  /// Load a GGUF model into the engine.
  ///
  /// Returns the load duration in seconds on success.
  Future<double> loadGgufModel(
      {required GgufModelConfig config,
      String? systemPrompt,
      SamplingConfig? sampling});

  /// Create a new engine with no model loaded.
  factory OndeChatEngine() => RustLib.instance.api.crateApiOndeChatEngineNew();

  /// Append a message to history without running inference.
  ///
  /// Useful for restoring a saved conversation or injecting context.
  Future<void> pushHistory({required ChatMessage message});

  /// Send a user message and receive a complete assistant reply.
  ///
  /// Both the user message and assistant reply are appended to the
  /// conversation history on success.
  Future<InferenceResult> sendMessage({required String message});

  /// Replace the sampling configuration used for all subsequent inference.
  Future<void> setSampling({required SamplingConfig sampling});

  /// Set or replace the system prompt.
  ///
  /// The prompt is prepended to every inference request and is **not**
  /// stored in the conversation history.
  Future<void> setSystemPrompt({required String prompt});

  /// Stream a reply token-by-token.
  ///
  /// Each [`StreamChunk`] carries a `delta` string.  The final chunk has
  /// `done == true`.  The `sink` is closed automatically when the stream
  /// ends or if the receiver is dropped.
  Stream<StreamChunk> streamMessage({required String message});

  /// Unload the current model and release its memory.
  ///
  /// Returns the display name of the model that was unloaded, or `None`
  /// if no model was loaded.
  Future<String?> unloadModel();
}

/// A single message in a conversation.
class ChatMessage {
  final ChatRole role;
  final String content;

  const ChatMessage({
    required this.role,
    required this.content,
  });

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// Role of a participant in a chat conversation.
enum ChatRole {
  system,
  user,
  assistant,
  ;
}

/// A point-in-time snapshot of the engine's state.
class EngineInfo {
  final EngineStatus status;

  /// Display name of the currently loaded model, if any.
  final String? modelName;

  /// Approximate memory footprint of the loaded model, if any.
  final String? approxMemory;

  /// Number of conversation turns in the current history.
  final BigInt historyLength;

  const EngineInfo({
    required this.status,
    this.modelName,
    this.approxMemory,
    required this.historyLength,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      modelName.hashCode ^
      approxMemory.hashCode ^
      historyLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineInfo &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          modelName == other.modelName &&
          approxMemory == other.approxMemory &&
          historyLength == other.historyLength;
}

/// Lifecycle status of the inference engine.
enum EngineStatus {
  unloaded,
  loading,
  ready,
  generating,
  error,
  ;
}

/// Configuration for loading a pre-quantised GGUF model.
class GgufModelConfig {
  /// HuggingFace repository ID, e.g. `"bartowski/Qwen2.5-1.5B-Instruct-GGUF"`.
  final String modelId;

  /// GGUF filename(s) within the repository.
  final List<String> files;

  /// Optional explicit tokenizer model ID (required on Android).
  final String? tokModelId;

  /// Human-friendly display name, e.g. `"Qwen 2.5 1.5B"`.
  final String displayName;

  /// Approximate memory footprint, e.g. `"~941 MB (GGUF Q4_K_M)"`.
  final String approxMemory;

  const GgufModelConfig({
    required this.modelId,
    required this.files,
    this.tokModelId,
    required this.displayName,
    required this.approxMemory,
  });

  @override
  int get hashCode =>
      modelId.hashCode ^
      files.hashCode ^
      tokModelId.hashCode ^
      displayName.hashCode ^
      approxMemory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GgufModelConfig &&
          runtimeType == other.runtimeType &&
          modelId == other.modelId &&
          files == other.files &&
          tokModelId == other.tokModelId &&
          displayName == other.displayName &&
          approxMemory == other.approxMemory;
}

/// The result of a completed inference request.
class InferenceResult {
  /// The generated assistant reply text.
  final String text;

  /// Wall-clock inference duration in seconds.
  final double durationSecs;

  /// Human-readable duration string, e.g. `"4.5s"` or `"2m 3.1s"`.
  final String durationDisplay;

  /// Finish reason reported by the model, e.g. `"stop"` or `"length"`.
  final String finishReason;

  const InferenceResult({
    required this.text,
    required this.durationSecs,
    required this.durationDisplay,
    required this.finishReason,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      durationSecs.hashCode ^
      durationDisplay.hashCode ^
      finishReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InferenceResult &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          durationSecs == other.durationSecs &&
          durationDisplay == other.durationDisplay &&
          finishReason == other.finishReason;
}

@freezed
sealed class OndeError with _$OndeError implements FrbException {
  const OndeError._();

  const factory OndeError.noModelLoaded() = OndeError_NoModelLoaded;
  const factory OndeError.alreadyLoaded({
    required String modelName,
  }) = OndeError_AlreadyLoaded;
  const factory OndeError.modelBuild({
    required String reason,
  }) = OndeError_ModelBuild;
  const factory OndeError.inference({
    required String reason,
  }) = OndeError_Inference;
  const factory OndeError.cancelled() = OndeError_Cancelled;
  const factory OndeError.other({
    required String reason,
  }) = OndeError_Other;
}

/// Sampling parameters for text generation.  All fields are optional — `None`
/// means "use the engine default".
class SamplingConfig {
  final double? temperature;
  final double? topP;
  final BigInt? topK;
  final double? minP;
  final BigInt? maxTokens;
  final double? frequencyPenalty;
  final double? presencePenalty;

  const SamplingConfig({
    this.temperature,
    this.topP,
    this.topK,
    this.minP,
    this.maxTokens,
    this.frequencyPenalty,
    this.presencePenalty,
  });

  @override
  int get hashCode =>
      temperature.hashCode ^
      topP.hashCode ^
      topK.hashCode ^
      minP.hashCode ^
      maxTokens.hashCode ^
      frequencyPenalty.hashCode ^
      presencePenalty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SamplingConfig &&
          runtimeType == other.runtimeType &&
          temperature == other.temperature &&
          topP == other.topP &&
          topK == other.topK &&
          minP == other.minP &&
          maxTokens == other.maxTokens &&
          frequencyPenalty == other.frequencyPenalty &&
          presencePenalty == other.presencePenalty;
}

/// A single streaming token chunk emitted during inference.
class StreamChunk {
  /// The token text delta (may be empty on the final chunk).
  final String delta;

  /// `true` when this is the last chunk in the stream.
  final bool done;

  /// Finish reason (set only on the final chunk).
  final String? finishReason;

  const StreamChunk({
    required this.delta,
    required this.done,
    this.finishReason,
  });

  @override
  int get hashCode => delta.hashCode ^ done.hashCode ^ finishReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamChunk &&
          runtimeType == other.runtimeType &&
          delta == other.delta &&
          done == other.done &&
          finishReason == other.finishReason;
}
