// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: type=lint, unused_import, unnecessary_import

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2058074152;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'onde_inference_dart',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiOndeChatEngineClearHistory(
      {required OndeChatEngine that});

  Future<void> crateApiOndeChatEngineClearSystemPrompt(
      {required OndeChatEngine that});

  Future<InferenceResult> crateApiOndeChatEngineGenerate(
      {required OndeChatEngine that,
      required List<ChatMessage> messages,
      SamplingConfig? sampling});

  Future<List<ChatMessage>> crateApiOndeChatEngineHistory(
      {required OndeChatEngine that});

  Future<EngineInfo> crateApiOndeChatEngineInfo({required OndeChatEngine that});

  Future<bool> crateApiOndeChatEngineIsLoaded({required OndeChatEngine that});

  Future<double> crateApiOndeChatEngineLoadGgufModel(
      {required OndeChatEngine that,
      required GgufModelConfig config,
      String? systemPrompt,
      SamplingConfig? sampling});

  OndeChatEngine crateApiOndeChatEngineNew();

  Future<void> crateApiOndeChatEnginePushHistory(
      {required OndeChatEngine that, required ChatMessage message});

  Future<InferenceResult> crateApiOndeChatEngineSendMessage(
      {required OndeChatEngine that, required String message});

  Future<void> crateApiOndeChatEngineSetSampling(
      {required OndeChatEngine that, required SamplingConfig sampling});

  Future<void> crateApiOndeChatEngineSetSystemPrompt(
      {required OndeChatEngine that, required String prompt});

  Stream<StreamChunk> crateApiOndeChatEngineStreamMessage(
      {required OndeChatEngine that, required String message});

  Future<String?> crateApiOndeChatEngineUnloadModel(
      {required OndeChatEngine that});

  GgufModelConfig crateApiDefaultModelConfig();

  SamplingConfig crateApiDefaultSamplingConfig();

  SamplingConfig crateApiDeterministicSamplingConfig();

  SamplingConfig crateApiMobileSamplingConfig();

  GgufModelConfig crateApiQwen2515BConfig();

  GgufModelConfig crateApiQwen253BConfig();

  GgufModelConfig crateApiQwen25Coder15BConfig();

  GgufModelConfig crateApiQwen25Coder3BConfig();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_OndeChatEngine;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_OndeChatEngine;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_OndeChatEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiOndeChatEngineClearHistory(
      {required OndeChatEngine that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineClearHistoryConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineClearHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_clear_history",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiOndeChatEngineClearSystemPrompt(
      {required OndeChatEngine that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineClearSystemPromptConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineClearSystemPromptConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_clear_system_prompt",
        argNames: ["that"],
      );

  @override
  Future<InferenceResult> crateApiOndeChatEngineGenerate(
      {required OndeChatEngine that,
      required List<ChatMessage> messages,
      SamplingConfig? sampling}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_list_chat_message(messages, serializer);
        sse_encode_opt_box_autoadd_sampling_config(sampling, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_inference_result,
        decodeErrorData: sse_decode_onde_error,
      ),
      constMeta: kCrateApiOndeChatEngineGenerateConstMeta,
      argValues: [that, messages, sampling],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineGenerateConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_generate",
        argNames: ["that", "messages", "sampling"],
      );

  @override
  Future<List<ChatMessage>> crateApiOndeChatEngineHistory(
      {required OndeChatEngine that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_chat_message,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineHistoryConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_history",
        argNames: ["that"],
      );

  @override
  Future<EngineInfo> crateApiOndeChatEngineInfo(
      {required OndeChatEngine that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_engine_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineInfoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineInfoConstMeta => const TaskConstMeta(
        debugName: "OndeChatEngine_info",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiOndeChatEngineIsLoaded({required OndeChatEngine that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineIsLoadedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineIsLoadedConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_is_loaded",
        argNames: ["that"],
      );

  @override
  Future<double> crateApiOndeChatEngineLoadGgufModel(
      {required OndeChatEngine that,
      required GgufModelConfig config,
      String? systemPrompt,
      SamplingConfig? sampling}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_box_autoadd_gguf_model_config(config, serializer);
        sse_encode_opt_String(systemPrompt, serializer);
        sse_encode_opt_box_autoadd_sampling_config(sampling, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: sse_decode_onde_error,
      ),
      constMeta: kCrateApiOndeChatEngineLoadGgufModelConstMeta,
      argValues: [that, config, systemPrompt, sampling],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineLoadGgufModelConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_load_gguf_model",
        argNames: ["that", "config", "systemPrompt", "sampling"],
      );

  @override
  OndeChatEngine crateApiOndeChatEngineNew() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineNewConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineNewConstMeta => const TaskConstMeta(
        debugName: "OndeChatEngine_new",
        argNames: [],
      );

  @override
  Future<void> crateApiOndeChatEnginePushHistory(
      {required OndeChatEngine that, required ChatMessage message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_box_autoadd_chat_message(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEnginePushHistoryConstMeta,
      argValues: [that, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEnginePushHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_push_history",
        argNames: ["that", "message"],
      );

  @override
  Future<InferenceResult> crateApiOndeChatEngineSendMessage(
      {required OndeChatEngine that, required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_inference_result,
        decodeErrorData: sse_decode_onde_error,
      ),
      constMeta: kCrateApiOndeChatEngineSendMessageConstMeta,
      argValues: [that, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_send_message",
        argNames: ["that", "message"],
      );

  @override
  Future<void> crateApiOndeChatEngineSetSampling(
      {required OndeChatEngine that, required SamplingConfig sampling}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_box_autoadd_sampling_config(sampling, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineSetSamplingConstMeta,
      argValues: [that, sampling],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineSetSamplingConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_set_sampling",
        argNames: ["that", "sampling"],
      );

  @override
  Future<void> crateApiOndeChatEngineSetSystemPrompt(
      {required OndeChatEngine that, required String prompt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_String(prompt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineSetSystemPromptConstMeta,
      argValues: [that, prompt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineSetSystemPromptConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_set_system_prompt",
        argNames: ["that", "prompt"],
      );

  @override
  Stream<StreamChunk> crateApiOndeChatEngineStreamMessage(
      {required OndeChatEngine that, required String message}) {
    final sink = RustStreamSink<StreamChunk>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        sse_encode_String(message, serializer);
        sse_encode_StreamSink_stream_chunk_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_onde_error,
      ),
      constMeta: kCrateApiOndeChatEngineStreamMessageConstMeta,
      argValues: [that, message, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOndeChatEngineStreamMessageConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_stream_message",
        argNames: ["that", "message", "sink"],
      );

  @override
  Future<String?> crateApiOndeChatEngineUnloadModel(
      {required OndeChatEngine that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOndeChatEngineUnloadModelConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOndeChatEngineUnloadModelConstMeta =>
      const TaskConstMeta(
        debugName: "OndeChatEngine_unload_model",
        argNames: ["that"],
      );

  @override
  GgufModelConfig crateApiDefaultModelConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gguf_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDefaultModelConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDefaultModelConfigConstMeta => const TaskConstMeta(
        debugName: "default_model_config",
        argNames: [],
      );

  @override
  SamplingConfig crateApiDefaultSamplingConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sampling_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDefaultSamplingConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDefaultSamplingConfigConstMeta =>
      const TaskConstMeta(
        debugName: "default_sampling_config",
        argNames: [],
      );

  @override
  SamplingConfig crateApiDeterministicSamplingConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sampling_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeterministicSamplingConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeterministicSamplingConfigConstMeta =>
      const TaskConstMeta(
        debugName: "deterministic_sampling_config",
        argNames: [],
      );

  @override
  SamplingConfig crateApiMobileSamplingConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sampling_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMobileSamplingConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobileSamplingConfigConstMeta =>
      const TaskConstMeta(
        debugName: "mobile_sampling_config",
        argNames: [],
      );

  @override
  GgufModelConfig crateApiQwen2515BConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gguf_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQwen2515BConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQwen2515BConfigConstMeta => const TaskConstMeta(
        debugName: "qwen25_1_5b_config",
        argNames: [],
      );

  @override
  GgufModelConfig crateApiQwen253BConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gguf_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQwen253BConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQwen253BConfigConstMeta => const TaskConstMeta(
        debugName: "qwen25_3b_config",
        argNames: [],
      );

  @override
  GgufModelConfig crateApiQwen25Coder15BConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gguf_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQwen25Coder15BConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQwen25Coder15BConfigConstMeta =>
      const TaskConstMeta(
        debugName: "qwen25_coder_1_5b_config",
        argNames: [],
      );

  @override
  GgufModelConfig crateApiQwen25Coder3BConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_gguf_model_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQwen25Coder3BConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQwen25Coder3BConfigConstMeta =>
      const TaskConstMeta(
        debugName: "qwen25_coder_3b_config",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_OndeChatEngine => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_OndeChatEngine => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  OndeChatEngine
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OndeChatEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OndeChatEngine
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OndeChatEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OndeChatEngine
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OndeChatEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<StreamChunk> dco_decode_StreamSink_stream_chunk_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_message(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GgufModelConfig dco_decode_box_autoadd_gguf_model_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gguf_model_config(raw);
  }

  @protected
  SamplingConfig dco_decode_box_autoadd_sampling_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sampling_config(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChatMessage(
      role: dco_decode_chat_role(arr[0]),
      content: dco_decode_String(arr[1]),
    );
  }

  @protected
  ChatRole dco_decode_chat_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatRole.values[raw as int];
  }

  @protected
  EngineInfo dco_decode_engine_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EngineInfo(
      status: dco_decode_engine_status(arr[0]),
      modelName: dco_decode_opt_String(arr[1]),
      approxMemory: dco_decode_opt_String(arr[2]),
      historyLength: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  EngineStatus dco_decode_engine_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineStatus.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GgufModelConfig dco_decode_gguf_model_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GgufModelConfig(
      modelId: dco_decode_String(arr[0]),
      files: dco_decode_list_String(arr[1]),
      tokModelId: dco_decode_opt_String(arr[2]),
      displayName: dco_decode_String(arr[3]),
      approxMemory: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InferenceResult dco_decode_inference_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InferenceResult(
      text: dco_decode_String(arr[0]),
      durationSecs: dco_decode_f_64(arr[1]),
      durationDisplay: dco_decode_String(arr[2]),
      finishReason: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OndeError dco_decode_onde_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return OndeError_NoModelLoaded();
      case 1:
        return OndeError_AlreadyLoaded(
          modelName: dco_decode_String(raw[1]),
        );
      case 2:
        return OndeError_ModelBuild(
          reason: dco_decode_String(raw[1]),
        );
      case 3:
        return OndeError_Inference(
          reason: dco_decode_String(raw[1]),
        );
      case 4:
        return OndeError_Cancelled();
      case 5:
        return OndeError_Other(
          reason: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  SamplingConfig? dco_decode_opt_box_autoadd_sampling_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_sampling_config(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SamplingConfig dco_decode_sampling_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SamplingConfig(
      temperature: dco_decode_opt_box_autoadd_f_64(arr[0]),
      topP: dco_decode_opt_box_autoadd_f_64(arr[1]),
      topK: dco_decode_opt_box_autoadd_u_64(arr[2]),
      minP: dco_decode_opt_box_autoadd_f_64(arr[3]),
      maxTokens: dco_decode_opt_box_autoadd_u_64(arr[4]),
      frequencyPenalty: dco_decode_opt_box_autoadd_f_32(arr[5]),
      presencePenalty: dco_decode_opt_box_autoadd_f_32(arr[6]),
    );
  }

  @protected
  StreamChunk dco_decode_stream_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StreamChunk(
      delta: dco_decode_String(arr[0]),
      done: dco_decode_bool(arr[1]),
      finishReason: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  OndeChatEngine
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OndeChatEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  OndeChatEngine
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OndeChatEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  OndeChatEngine
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OndeChatEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<StreamChunk> sse_decode_StreamSink_stream_chunk_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_message(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  GgufModelConfig sse_decode_box_autoadd_gguf_model_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gguf_model_config(deserializer));
  }

  @protected
  SamplingConfig sse_decode_box_autoadd_sampling_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sampling_config(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_chat_role(deserializer);
    var var_content = sse_decode_String(deserializer);
    return ChatMessage(role: var_role, content: var_content);
  }

  @protected
  ChatRole sse_decode_chat_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ChatRole.values[inner];
  }

  @protected
  EngineInfo sse_decode_engine_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_engine_status(deserializer);
    var var_modelName = sse_decode_opt_String(deserializer);
    var var_approxMemory = sse_decode_opt_String(deserializer);
    var var_historyLength = sse_decode_u_64(deserializer);
    return EngineInfo(
        status: var_status,
        modelName: var_modelName,
        approxMemory: var_approxMemory,
        historyLength: var_historyLength);
  }

  @protected
  EngineStatus sse_decode_engine_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EngineStatus.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GgufModelConfig sse_decode_gguf_model_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelId = sse_decode_String(deserializer);
    var var_files = sse_decode_list_String(deserializer);
    var var_tokModelId = sse_decode_opt_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_approxMemory = sse_decode_String(deserializer);
    return GgufModelConfig(
        modelId: var_modelId,
        files: var_files,
        tokModelId: var_tokModelId,
        displayName: var_displayName,
        approxMemory: var_approxMemory);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InferenceResult sse_decode_inference_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_durationSecs = sse_decode_f_64(deserializer);
    var var_durationDisplay = sse_decode_String(deserializer);
    var var_finishReason = sse_decode_String(deserializer);
    return InferenceResult(
        text: var_text,
        durationSecs: var_durationSecs,
        durationDisplay: var_durationDisplay,
        finishReason: var_finishReason);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OndeError sse_decode_onde_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return OndeError_NoModelLoaded();
      case 1:
        var var_modelName = sse_decode_String(deserializer);
        return OndeError_AlreadyLoaded(modelName: var_modelName);
      case 2:
        var var_reason = sse_decode_String(deserializer);
        return OndeError_ModelBuild(reason: var_reason);
      case 3:
        var var_reason = sse_decode_String(deserializer);
        return OndeError_Inference(reason: var_reason);
      case 4:
        return OndeError_Cancelled();
      case 5:
        var var_reason = sse_decode_String(deserializer);
        return OndeError_Other(reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SamplingConfig? sse_decode_opt_box_autoadd_sampling_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_sampling_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SamplingConfig sse_decode_sampling_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_temperature = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_topP = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_topK = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_minP = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_maxTokens = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_frequencyPenalty = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_presencePenalty = sse_decode_opt_box_autoadd_f_32(deserializer);
    return SamplingConfig(
        temperature: var_temperature,
        topP: var_topP,
        topK: var_topK,
        minP: var_minP,
        maxTokens: var_maxTokens,
        frequencyPenalty: var_frequencyPenalty,
        presencePenalty: var_presencePenalty);
  }

  @protected
  StreamChunk sse_decode_stream_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_delta = sse_decode_String(deserializer);
    var var_done = sse_decode_bool(deserializer);
    var var_finishReason = sse_decode_opt_String(deserializer);
    return StreamChunk(
        delta: var_delta, done: var_done, finishReason: var_finishReason);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          OndeChatEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as OndeChatEngineImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          OndeChatEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as OndeChatEngineImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOndeChatEngine(
          OndeChatEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as OndeChatEngineImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_stream_chunk_Sse(
      RustStreamSink<StreamChunk> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_stream_chunk,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chat_message(
      ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gguf_model_config(
      GgufModelConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gguf_model_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sampling_config(
      SamplingConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sampling_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_role(self.role, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_chat_role(ChatRole self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_engine_info(EngineInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_engine_status(self.status, serializer);
    sse_encode_opt_String(self.modelName, serializer);
    sse_encode_opt_String(self.approxMemory, serializer);
    sse_encode_u_64(self.historyLength, serializer);
  }

  @protected
  void sse_encode_engine_status(EngineStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_gguf_model_config(
      GgufModelConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelId, serializer);
    sse_encode_list_String(self.files, serializer);
    sse_encode_opt_String(self.tokModelId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.approxMemory, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_inference_result(
      InferenceResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_f_64(self.durationSecs, serializer);
    sse_encode_String(self.durationDisplay, serializer);
    sse_encode_String(self.finishReason, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(
      List<ChatMessage> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_onde_error(OndeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case OndeError_NoModelLoaded():
        sse_encode_i_32(0, serializer);
      case OndeError_AlreadyLoaded(modelName: final modelName):
        sse_encode_i_32(1, serializer);
        sse_encode_String(modelName, serializer);
      case OndeError_ModelBuild(reason: final reason):
        sse_encode_i_32(2, serializer);
        sse_encode_String(reason, serializer);
      case OndeError_Inference(reason: final reason):
        sse_encode_i_32(3, serializer);
        sse_encode_String(reason, serializer);
      case OndeError_Cancelled():
        sse_encode_i_32(4, serializer);
      case OndeError_Other(reason: final reason):
        sse_encode_i_32(5, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_sampling_config(
      SamplingConfig? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_sampling_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_sampling_config(
      SamplingConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_64(self.temperature, serializer);
    sse_encode_opt_box_autoadd_f_64(self.topP, serializer);
    sse_encode_opt_box_autoadd_u_64(self.topK, serializer);
    sse_encode_opt_box_autoadd_f_64(self.minP, serializer);
    sse_encode_opt_box_autoadd_u_64(self.maxTokens, serializer);
    sse_encode_opt_box_autoadd_f_32(self.frequencyPenalty, serializer);
    sse_encode_opt_box_autoadd_f_32(self.presencePenalty, serializer);
  }

  @protected
  void sse_encode_stream_chunk(StreamChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.delta, serializer);
    sse_encode_bool(self.done, serializer);
    sse_encode_opt_String(self.finishReason, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class OndeChatEngineImpl extends RustOpaque implements OndeChatEngine {
  // Not to be used by end users
  OndeChatEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OndeChatEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_OndeChatEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_OndeChatEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_OndeChatEnginePtr,
  );

  /// Clear the conversation history while keeping the model loaded.
  ///
  /// Returns the number of turns that were removed.
  Future<BigInt> clearHistory() =>
      RustLib.instance.api.crateApiOndeChatEngineClearHistory(
        that: this,
      );

  /// Clear the current system prompt.
  Future<void> clearSystemPrompt() =>
      RustLib.instance.api.crateApiOndeChatEngineClearSystemPrompt(
        that: this,
      );

  /// One-shot generation from an explicit message list.
  ///
  /// Does **not** modify the conversation history.
  Future<InferenceResult> generate(
          {required List<ChatMessage> messages, SamplingConfig? sampling}) =>
      RustLib.instance.api.crateApiOndeChatEngineGenerate(
          that: this, messages: messages, sampling: sampling);

  /// Returns a clone of the full conversation history.
  Future<List<ChatMessage>> history() =>
      RustLib.instance.api.crateApiOndeChatEngineHistory(
        that: this,
      );

  /// Returns a point-in-time snapshot of the engine's state.
  Future<EngineInfo> info() => RustLib.instance.api.crateApiOndeChatEngineInfo(
        that: this,
      );

  /// Returns `true` if a model is currently loaded and ready.
  Future<bool> isLoaded() =>
      RustLib.instance.api.crateApiOndeChatEngineIsLoaded(
        that: this,
      );

  /// Load a GGUF model into the engine.
  ///
  /// Returns the load duration in seconds on success.
  Future<double> loadGgufModel(
          {required GgufModelConfig config,
          String? systemPrompt,
          SamplingConfig? sampling}) =>
      RustLib.instance.api.crateApiOndeChatEngineLoadGgufModel(
          that: this,
          config: config,
          systemPrompt: systemPrompt,
          sampling: sampling);

  /// Append a message to history without running inference.
  ///
  /// Useful for restoring a saved conversation or injecting context.
  Future<void> pushHistory({required ChatMessage message}) =>
      RustLib.instance.api
          .crateApiOndeChatEnginePushHistory(that: this, message: message);

  /// Send a user message and receive a complete assistant reply.
  ///
  /// Both the user message and assistant reply are appended to the
  /// conversation history on success.
  Future<InferenceResult> sendMessage({required String message}) =>
      RustLib.instance.api
          .crateApiOndeChatEngineSendMessage(that: this, message: message);

  /// Replace the sampling configuration used for all subsequent inference.
  Future<void> setSampling({required SamplingConfig sampling}) =>
      RustLib.instance.api
          .crateApiOndeChatEngineSetSampling(that: this, sampling: sampling);

  /// Set or replace the system prompt.
  ///
  /// The prompt is prepended to every inference request and is **not**
  /// stored in the conversation history.
  Future<void> setSystemPrompt({required String prompt}) => RustLib.instance.api
      .crateApiOndeChatEngineSetSystemPrompt(that: this, prompt: prompt);

  /// Stream a reply token-by-token.
  ///
  /// Each [`StreamChunk`] carries a `delta` string.  The final chunk has
  /// `done == true`.  The `sink` is closed automatically when the stream
  /// ends or if the receiver is dropped.
  Stream<StreamChunk> streamMessage({required String message}) =>
      RustLib.instance.api
          .crateApiOndeChatEngineStreamMessage(that: this, message: message);

  /// Unload the current model and release its memory.
  ///
  /// Returns the display name of the model that was unloaded, or `None`
  /// if no model was loaded.
  Future<String?> unloadModel() =>
      RustLib.instance.api.crateApiOndeChatEngineUnloadModel(
        that: this,
      );
}
